# Generated by Django 5.2.6 on 2025-12-08 02:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цеха')),
            ],
            options={
                'verbose_name': 'Сборочный цех',
                'verbose_name_plural': 'Сборочные цехи',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(blank=True, choices=[('master', 'Мастер'), ('technolog', 'Технолог'), ('admin', 'Администратор')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('assembly_shops', models.ManyToManyField(to='api.assemblyshop', verbose_name='Рабочие цехи')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название заказа')),
                ('description', models.TextField(verbose_name='Описание/Чертеж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Операция', max_length=255, verbose_name='Название операции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание операции')),
                ('priority', models.IntegerField(verbose_name='Приоритет в сборочном цехе')),
                ('planned_start', models.DateTimeField(verbose_name='Плановая дата начала')),
                ('planned_end', models.DateTimeField(verbose_name='Плановая дата окончания')),
                ('actual_planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Актуальная дата окончания')),
                ('actual_planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Актуальная дата начала')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата начала')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('needs_master_check', models.BooleanField(default=False, verbose_name='Требуется проверка мастером')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('assembly_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblyshop', verbose_name='Сборочный цех')),
                ('executors', models.ManyToManyField(to='api.executor', verbose_name='Исполнители')),
                ('master_checker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['priority'],
                'indexes': [models.Index(fields=['order', 'priority'], name='api_operati_order_i_3847b9_idx'), models.Index(fields=['assembly_shop', 'planned_start'], name='api_operati_assembl_28bed1_idx')],
            },
        ),
    ]
