# Generated by Django 5.2.6 on 2025-11-18 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цеха')),
            ],
            options={
                'verbose_name': 'Сборочный цех',
                'verbose_name_plural': 'Сборочные цехи',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('assembly_shops', models.ManyToManyField(to='api.assemblyshop', verbose_name='Рабочие цехи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название заказа')),
                ('description', models.TextField(verbose_name='Описание/Чертеж')),
                ('priority', models.IntegerField(verbose_name='Приоритет среди заказов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Приоритет в заказе')),
                ('planned_start', models.DateTimeField(verbose_name='Плановая дата начала')),
                ('planned_end', models.DateTimeField(verbose_name='Плановая дата окончания')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата начала')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата окончания')),
                ('needs_master_check', models.BooleanField(default=False, verbose_name='Требуется проверка мастером')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('assembly_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assemblyshop', verbose_name='Сборочный цех')),
                ('executors', models.ManyToManyField(to='api.executor', verbose_name='Исполнители')),
                ('master_checker', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Мастер'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий мастер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='api.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['order__priority', 'priority'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['priority', 'created_at'], name='api_order_priorit_85c6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['order', 'priority'], name='api_operati_order_i_3847b9_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['assembly_shop', 'planned_start'], name='api_operati_assembl_28bed1_idx'),
        ),
    ]
