# Generated by Django 5.2.6 on 2025-11-18 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание операции'),
        ),
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(default='Операция', max_length=255, verbose_name='Название операции'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='master_checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий'),
        ),
    ]
