# Generated by Django 5.2.6 on 2025-12-17 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_deadline_alter_order_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TehLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('info', models.CharField(max_length=256, verbose_name='Информация')),
                ('type', models.IntegerField(choices=[(0, 'Late'), (1, 'Ahead')], verbose_name='Тип лога')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
