# Generated by Django 5.2.6 on 2025-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_operation_description_operation_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['priority'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='api_order_priorit_85c6bf_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='priority',
        ),
        migrations.AlterField(
            model_name='operation',
            name='priority',
            field=models.IntegerField(verbose_name='Приоритет в сборочном цехе'),
        ),
    ]
