# Generated by Django 5.2.6 on 2025-11-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_operation_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='user',
        ),
    ]
