# Generated by Django 5.2.6 on 2025-12-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tehlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tehlog',
            name='type',
            field=models.IntegerField(choices=[(0, 'Late Start'), (1, 'Late Stop'), (2, 'Ahead Start'), (3, 'Ahead Stop')], verbose_name='Тип лога'),
        ),
    ]
