# Generated by Django 5.2.6 on 2025-12-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tehlog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='next_operation',
        ),
        migrations.AddField(
            model_name='operation',
            name='previous_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_operations', to='api.operation', verbose_name='Предыдущая операция'),
        ),
    ]
