# Generated by Django 5.2.6 on 2025-11-25 22:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_executor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='actual_planned_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Актуальная дата окончания'),
        ),
    ]
