# Generated by Django 5.2.6 on 2025-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_operation_next_operation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='operation_set', to='api.executor', verbose_name='Исполнители'),
        ),
    ]
